export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>ListaTareas</title>
  <base href="/ListaTareas/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles-5INURTSO.css"><style ng-app-id="ng">.listaTareas-contenedor[_ngcontent-ng-c3378331007]{width:100%;max-width:600px;margin:0 auto;padding:20px;background-color:#f9f9f9;border-radius:8px;box-shadow:0 2px 10px #0000001a}h2[_ngcontent-ng-c3378331007]{text-align:center;color:#333}input[type=text][_ngcontent-ng-c3378331007]{width:80px;padding:10px;margin-right:10px;border-radius:4px;border:1px solid #ccc;font-size:16px}.agregar-boton[_ngcontent-ng-c3378331007]{padding:10px 15px;margin:15px;background-color:#fff;border-radius:5px;cursor:pointer;font-size:16px}.agregar-boton[_ngcontent-ng-c3378331007]:hover{background-color:#5999de}ul[_ngcontent-ng-c3378331007]{list-style-type:none;padding:0;margin-top:20px}li[_ngcontent-ng-c3378331007]{display:flex;justify-content:space-between;align-items:center;background-color:#fff;padding:10px;margin-bottom:10px;border:1px solid #ddd;border-radius:4px}.eliminar-boton[_ngcontent-ng-c3378331007]{padding:10px 15px;background-color:#dc3545;color:#fff;border:none;cursor:pointer;font-size:16px;border:1px solid #333;border-radius:4px}.eliminar-boton[_ngcontent-ng-c3378331007]:hover{background-color:#c82333}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["input","compositionstart","compositionend","click"],["blur"]);</script>
  <app-root ng-version="19.0.6" ngh="1" ng-server-context="ssg"><app-lista-tareas _nghost-ng-c3378331007 ngh="0"><div _ngcontent-ng-c3378331007 class="listaTareas-container"><h2 _ngcontent-ng-c3378331007>Lista de Tareas</h2><div _ngcontent-ng-c3378331007><input _ngcontent-ng-c3378331007 placeholder="Nueva tarea" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><button _ngcontent-ng-c3378331007 class="agregar-boton" jsaction="click:;">Agregar tarea</button></div><ul _ngcontent-ng-c3378331007><!----></ul></div></app-lista-tareas></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-7M2X33AR.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{"t":{"8":"t0"},"c":{"8":[]}},{}]}</script></body></html>`;